// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: protobuf/search/search_games.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - search.SearchGamesService

/// Namespace containing generated types for the "search.SearchGamesService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Search_SearchGamesService: Sendable {
    /// Service descriptor for the "search.SearchGamesService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "search.SearchGamesService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "SearchGames" metadata.
        public enum SearchGames: Sendable {
            /// Request type for "SearchGames".
            public typealias Input = Search_SearchGamesRequest
            /// Response type for "SearchGames".
            public typealias Output = Search_SearchGamesResponse
            /// Descriptor for "SearchGames".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "search.SearchGamesService"),
                method: "SearchGames",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "search.SearchGamesService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            SearchGames.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "search.SearchGamesService" service.
    public static let search_SearchGamesService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "search.SearchGamesService")
}

// MARK: search.SearchGamesService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchGamesService {
    /// Streaming variant of the service protocol for the "search.SearchGamesService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchGamesService provides game search for client applications.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "SearchGames" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Search_SearchGamesRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Search_SearchGamesResponse` messages.
        func searchGames(
            request: GRPCCore.StreamingServerRequest<Search_SearchGamesRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Search_SearchGamesResponse>
    }

    /// Service protocol for the "search.SearchGamesService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchGamesService provides game search for client applications.
    public protocol ServiceProtocol: Search_SearchGamesService.StreamingServiceProtocol {
        /// Handle the "SearchGames" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Search_SearchGamesRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Search_SearchGamesResponse` message.
        func searchGames(
            request: GRPCCore.ServerRequest<Search_SearchGamesRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Search_SearchGamesResponse>
    }

    /// Simple service protocol for the "search.SearchGamesService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchGamesService provides game search for client applications.
    public protocol SimpleServiceProtocol: Search_SearchGamesService.ServiceProtocol {
        /// Handle the "SearchGames" method.
        ///
        /// - Parameters:
        ///   - request: A `Search_SearchGamesRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Search_SearchGamesResponse` to respond with.
        func searchGames(
            request: Search_SearchGamesRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Search_SearchGamesResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchGamesService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Search_SearchGamesService.Method.SearchGames.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Search_SearchGamesRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Search_SearchGamesResponse>(),
            handler: { request, context in
                try await self.searchGames(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchGamesService.ServiceProtocol {
    public func searchGames(
        request: GRPCCore.StreamingServerRequest<Search_SearchGamesRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Search_SearchGamesResponse> {
        let response = try await self.searchGames(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchGamesService.SimpleServiceProtocol {
    public func searchGames(
        request: GRPCCore.ServerRequest<Search_SearchGamesRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Search_SearchGamesResponse> {
        return GRPCCore.ServerResponse<Search_SearchGamesResponse>(
            message: try await self.searchGames(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: search.SearchGamesService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchGamesService {
    /// Generated client protocol for the "search.SearchGamesService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchGamesService provides game search for client applications.
    public protocol ClientProtocol: Sendable {
        /// Call the "SearchGames" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Search_SearchGamesRequest` message.
        ///   - serializer: A serializer for `Search_SearchGamesRequest` messages.
        ///   - deserializer: A deserializer for `Search_SearchGamesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func searchGames<Result>(
            request: GRPCCore.ClientRequest<Search_SearchGamesRequest>,
            serializer: some GRPCCore.MessageSerializer<Search_SearchGamesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Search_SearchGamesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Search_SearchGamesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "search.SearchGamesService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchGamesService provides game search for client applications.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SearchGames" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Search_SearchGamesRequest` message.
        ///   - serializer: A serializer for `Search_SearchGamesRequest` messages.
        ///   - deserializer: A deserializer for `Search_SearchGamesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func searchGames<Result>(
            request: GRPCCore.ClientRequest<Search_SearchGamesRequest>,
            serializer: some GRPCCore.MessageSerializer<Search_SearchGamesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Search_SearchGamesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Search_SearchGamesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Search_SearchGamesService.Method.SearchGames.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchGamesService.ClientProtocol {
    /// Call the "SearchGames" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Search_SearchGamesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func searchGames<Result>(
        request: GRPCCore.ClientRequest<Search_SearchGamesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Search_SearchGamesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.searchGames(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Search_SearchGamesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Search_SearchGamesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchGamesService.ClientProtocol {
    /// Call the "SearchGames" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func searchGames<Result>(
        _ message: Search_SearchGamesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Search_SearchGamesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Search_SearchGamesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.searchGames(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}