// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: protobuf/search/search_products.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - search.SearchProductsService

/// Namespace containing generated types for the "search.SearchProductsService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Search_SearchProductsService: Sendable {
    /// Service descriptor for the "search.SearchProductsService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "search.SearchProductsService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "SearchProducts" metadata.
        public enum SearchProducts: Sendable {
            /// Request type for "SearchProducts".
            public typealias Input = Search_SearchProductsRequest
            /// Response type for "SearchProducts".
            public typealias Output = Search_SearchProductsResponse
            /// Descriptor for "SearchProducts".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "search.SearchProductsService"),
                method: "SearchProducts",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "search.SearchProductsService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            SearchProducts.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "search.SearchProductsService" service.
    public static let search_SearchProductsService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "search.SearchProductsService")
}

// MARK: search.SearchProductsService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchProductsService {
    /// Streaming variant of the service protocol for the "search.SearchProductsService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchProductsService provides food product search for Eatometer.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "SearchProducts" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Search_SearchProductsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Search_SearchProductsResponse` messages.
        func searchProducts(
            request: GRPCCore.StreamingServerRequest<Search_SearchProductsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Search_SearchProductsResponse>
    }

    /// Service protocol for the "search.SearchProductsService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchProductsService provides food product search for Eatometer.
    public protocol ServiceProtocol: Search_SearchProductsService.StreamingServiceProtocol {
        /// Handle the "SearchProducts" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Search_SearchProductsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Search_SearchProductsResponse` message.
        func searchProducts(
            request: GRPCCore.ServerRequest<Search_SearchProductsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Search_SearchProductsResponse>
    }

    /// Simple service protocol for the "search.SearchProductsService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchProductsService provides food product search for Eatometer.
    public protocol SimpleServiceProtocol: Search_SearchProductsService.ServiceProtocol {
        /// Handle the "SearchProducts" method.
        ///
        /// - Parameters:
        ///   - request: A `Search_SearchProductsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Search_SearchProductsResponse` to respond with.
        func searchProducts(
            request: Search_SearchProductsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Search_SearchProductsResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchProductsService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Search_SearchProductsService.Method.SearchProducts.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Search_SearchProductsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Search_SearchProductsResponse>(),
            handler: { request, context in
                try await self.searchProducts(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchProductsService.ServiceProtocol {
    public func searchProducts(
        request: GRPCCore.StreamingServerRequest<Search_SearchProductsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Search_SearchProductsResponse> {
        let response = try await self.searchProducts(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchProductsService.SimpleServiceProtocol {
    public func searchProducts(
        request: GRPCCore.ServerRequest<Search_SearchProductsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Search_SearchProductsResponse> {
        return GRPCCore.ServerResponse<Search_SearchProductsResponse>(
            message: try await self.searchProducts(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: search.SearchProductsService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchProductsService {
    /// Generated client protocol for the "search.SearchProductsService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchProductsService provides food product search for Eatometer.
    public protocol ClientProtocol: Sendable {
        /// Call the "SearchProducts" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Search_SearchProductsRequest` message.
        ///   - serializer: A serializer for `Search_SearchProductsRequest` messages.
        ///   - deserializer: A deserializer for `Search_SearchProductsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func searchProducts<Result>(
            request: GRPCCore.ClientRequest<Search_SearchProductsRequest>,
            serializer: some GRPCCore.MessageSerializer<Search_SearchProductsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Search_SearchProductsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Search_SearchProductsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "search.SearchProductsService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SearchProductsService provides food product search for Eatometer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SearchProducts" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Search_SearchProductsRequest` message.
        ///   - serializer: A serializer for `Search_SearchProductsRequest` messages.
        ///   - deserializer: A deserializer for `Search_SearchProductsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func searchProducts<Result>(
            request: GRPCCore.ClientRequest<Search_SearchProductsRequest>,
            serializer: some GRPCCore.MessageSerializer<Search_SearchProductsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Search_SearchProductsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Search_SearchProductsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Search_SearchProductsService.Method.SearchProducts.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchProductsService.ClientProtocol {
    /// Call the "SearchProducts" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Search_SearchProductsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func searchProducts<Result>(
        request: GRPCCore.ClientRequest<Search_SearchProductsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Search_SearchProductsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.searchProducts(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Search_SearchProductsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Search_SearchProductsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Search_SearchProductsService.ClientProtocol {
    /// Call the "SearchProducts" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func searchProducts<Result>(
        _ message: Search_SearchProductsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Search_SearchProductsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Search_SearchProductsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.searchProducts(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}