// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: protobuf/admin/admin.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - admin.AdminService

/// Namespace containing generated types for the "admin.AdminService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Admin_AdminService: Sendable {
    /// Service descriptor for the "admin.AdminService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "SendNewsletter" metadata.
        public enum SendNewsletter: Sendable {
            /// Request type for "SendNewsletter".
            public typealias Input = Admin_SendNewsletterRequest
            /// Response type for "SendNewsletter".
            public typealias Output = Admin_SendNewsletterResponse
            /// Descriptor for "SendNewsletter".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService"),
                method: "SendNewsletter",
                type: .unary
            )
        }
        /// Namespace for "SendNewsPush" metadata.
        public enum SendNewsPush: Sendable {
            /// Request type for "SendNewsPush".
            public typealias Input = Admin_SendNewsPushRequest
            /// Response type for "SendNewsPush".
            public typealias Output = Admin_SendNewsPushResponse
            /// Descriptor for "SendNewsPush".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService"),
                method: "SendNewsPush",
                type: .unary
            )
        }
        /// Namespace for "CreateSupportRequest" metadata.
        public enum CreateSupportRequest: Sendable {
            /// Request type for "CreateSupportRequest".
            public typealias Input = Admin_CreateSupportRequestRequest
            /// Response type for "CreateSupportRequest".
            public typealias Output = Admin_CreateSupportRequestResponse
            /// Descriptor for "CreateSupportRequest".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService"),
                method: "CreateSupportRequest",
                type: .unary
            )
        }
        /// Namespace for "ListSupportRequests" metadata.
        public enum ListSupportRequests: Sendable {
            /// Request type for "ListSupportRequests".
            public typealias Input = Admin_ListSupportRequestsRequest
            /// Response type for "ListSupportRequests".
            public typealias Output = Admin_ListSupportRequestsResponse
            /// Descriptor for "ListSupportRequests".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService"),
                method: "ListSupportRequests",
                type: .unary
            )
        }
        /// Namespace for "ReplySupportRequest" metadata.
        public enum ReplySupportRequest: Sendable {
            /// Request type for "ReplySupportRequest".
            public typealias Input = Admin_ReplySupportRequestRequest
            /// Response type for "ReplySupportRequest".
            public typealias Output = Admin_ReplySupportRequestResponse
            /// Descriptor for "ReplySupportRequest".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService"),
                method: "ReplySupportRequest",
                type: .unary
            )
        }
        /// Namespace for "ListUsers" metadata.
        public enum ListUsers: Sendable {
            /// Request type for "ListUsers".
            public typealias Input = Admin_ListUsersRequest
            /// Response type for "ListUsers".
            public typealias Output = Admin_ListUsersResponse
            /// Descriptor for "ListUsers".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService"),
                method: "ListUsers",
                type: .unary
            )
        }
        /// Namespace for "BanUser" metadata.
        public enum BanUser: Sendable {
            /// Request type for "BanUser".
            public typealias Input = Admin_BanUserRequest
            /// Response type for "BanUser".
            public typealias Output = Admin_BanUserResponse
            /// Descriptor for "BanUser".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService"),
                method: "BanUser",
                type: .unary
            )
        }
        /// Namespace for "UnbanUser" metadata.
        public enum UnbanUser: Sendable {
            /// Request type for "UnbanUser".
            public typealias Input = Admin_UnbanUserRequest
            /// Response type for "UnbanUser".
            public typealias Output = Admin_UnbanUserResponse
            /// Descriptor for "UnbanUser".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService"),
                method: "UnbanUser",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "admin.AdminService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            SendNewsletter.descriptor,
            SendNewsPush.descriptor,
            CreateSupportRequest.descriptor,
            ListSupportRequests.descriptor,
            ReplySupportRequest.descriptor,
            ListUsers.descriptor,
            BanUser.descriptor,
            UnbanUser.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "admin.AdminService" service.
    public static let admin_AdminService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "admin.AdminService")
}

// MARK: admin.AdminService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Admin_AdminService {
    /// Streaming variant of the service protocol for the "admin.AdminService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "SendNewsletter" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Admin_SendNewsletterRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Admin_SendNewsletterResponse` messages.
        func sendNewsletter(
            request: GRPCCore.StreamingServerRequest<Admin_SendNewsletterRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Admin_SendNewsletterResponse>

        /// Handle the "SendNewsPush" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Admin_SendNewsPushRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Admin_SendNewsPushResponse` messages.
        func sendNewsPush(
            request: GRPCCore.StreamingServerRequest<Admin_SendNewsPushRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Admin_SendNewsPushResponse>

        /// Handle the "CreateSupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Admin_CreateSupportRequestRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Admin_CreateSupportRequestResponse` messages.
        func createSupportRequest(
            request: GRPCCore.StreamingServerRequest<Admin_CreateSupportRequestRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Admin_CreateSupportRequestResponse>

        /// Handle the "ListSupportRequests" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Admin_ListSupportRequestsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Admin_ListSupportRequestsResponse` messages.
        func listSupportRequests(
            request: GRPCCore.StreamingServerRequest<Admin_ListSupportRequestsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Admin_ListSupportRequestsResponse>

        /// Handle the "ReplySupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Admin_ReplySupportRequestRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Admin_ReplySupportRequestResponse` messages.
        func replySupportRequest(
            request: GRPCCore.StreamingServerRequest<Admin_ReplySupportRequestRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Admin_ReplySupportRequestResponse>

        /// Handle the "ListUsers" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Admin_ListUsersRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Admin_ListUsersResponse` messages.
        func listUsers(
            request: GRPCCore.StreamingServerRequest<Admin_ListUsersRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Admin_ListUsersResponse>

        /// Handle the "BanUser" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Admin_BanUserRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Admin_BanUserResponse` messages.
        func banUser(
            request: GRPCCore.StreamingServerRequest<Admin_BanUserRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Admin_BanUserResponse>

        /// Handle the "UnbanUser" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Admin_UnbanUserRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Admin_UnbanUserResponse` messages.
        func unbanUser(
            request: GRPCCore.StreamingServerRequest<Admin_UnbanUserRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Admin_UnbanUserResponse>
    }

    /// Service protocol for the "admin.AdminService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Admin_AdminService.StreamingServiceProtocol {
        /// Handle the "SendNewsletter" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_SendNewsletterRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Admin_SendNewsletterResponse` message.
        func sendNewsletter(
            request: GRPCCore.ServerRequest<Admin_SendNewsletterRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Admin_SendNewsletterResponse>

        /// Handle the "SendNewsPush" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_SendNewsPushRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Admin_SendNewsPushResponse` message.
        func sendNewsPush(
            request: GRPCCore.ServerRequest<Admin_SendNewsPushRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Admin_SendNewsPushResponse>

        /// Handle the "CreateSupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_CreateSupportRequestRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Admin_CreateSupportRequestResponse` message.
        func createSupportRequest(
            request: GRPCCore.ServerRequest<Admin_CreateSupportRequestRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Admin_CreateSupportRequestResponse>

        /// Handle the "ListSupportRequests" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_ListSupportRequestsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Admin_ListSupportRequestsResponse` message.
        func listSupportRequests(
            request: GRPCCore.ServerRequest<Admin_ListSupportRequestsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Admin_ListSupportRequestsResponse>

        /// Handle the "ReplySupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_ReplySupportRequestRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Admin_ReplySupportRequestResponse` message.
        func replySupportRequest(
            request: GRPCCore.ServerRequest<Admin_ReplySupportRequestRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Admin_ReplySupportRequestResponse>

        /// Handle the "ListUsers" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_ListUsersRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Admin_ListUsersResponse` message.
        func listUsers(
            request: GRPCCore.ServerRequest<Admin_ListUsersRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Admin_ListUsersResponse>

        /// Handle the "BanUser" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_BanUserRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Admin_BanUserResponse` message.
        func banUser(
            request: GRPCCore.ServerRequest<Admin_BanUserRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Admin_BanUserResponse>

        /// Handle the "UnbanUser" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_UnbanUserRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Admin_UnbanUserResponse` message.
        func unbanUser(
            request: GRPCCore.ServerRequest<Admin_UnbanUserRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Admin_UnbanUserResponse>
    }

    /// Simple service protocol for the "admin.AdminService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Admin_AdminService.ServiceProtocol {
        /// Handle the "SendNewsletter" method.
        ///
        /// - Parameters:
        ///   - request: A `Admin_SendNewsletterRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Admin_SendNewsletterResponse` to respond with.
        func sendNewsletter(
            request: Admin_SendNewsletterRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Admin_SendNewsletterResponse

        /// Handle the "SendNewsPush" method.
        ///
        /// - Parameters:
        ///   - request: A `Admin_SendNewsPushRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Admin_SendNewsPushResponse` to respond with.
        func sendNewsPush(
            request: Admin_SendNewsPushRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Admin_SendNewsPushResponse

        /// Handle the "CreateSupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A `Admin_CreateSupportRequestRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Admin_CreateSupportRequestResponse` to respond with.
        func createSupportRequest(
            request: Admin_CreateSupportRequestRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Admin_CreateSupportRequestResponse

        /// Handle the "ListSupportRequests" method.
        ///
        /// - Parameters:
        ///   - request: A `Admin_ListSupportRequestsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Admin_ListSupportRequestsResponse` to respond with.
        func listSupportRequests(
            request: Admin_ListSupportRequestsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Admin_ListSupportRequestsResponse

        /// Handle the "ReplySupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A `Admin_ReplySupportRequestRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Admin_ReplySupportRequestResponse` to respond with.
        func replySupportRequest(
            request: Admin_ReplySupportRequestRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Admin_ReplySupportRequestResponse

        /// Handle the "ListUsers" method.
        ///
        /// - Parameters:
        ///   - request: A `Admin_ListUsersRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Admin_ListUsersResponse` to respond with.
        func listUsers(
            request: Admin_ListUsersRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Admin_ListUsersResponse

        /// Handle the "BanUser" method.
        ///
        /// - Parameters:
        ///   - request: A `Admin_BanUserRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Admin_BanUserResponse` to respond with.
        func banUser(
            request: Admin_BanUserRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Admin_BanUserResponse

        /// Handle the "UnbanUser" method.
        ///
        /// - Parameters:
        ///   - request: A `Admin_UnbanUserRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Admin_UnbanUserResponse` to respond with.
        func unbanUser(
            request: Admin_UnbanUserRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Admin_UnbanUserResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Admin_AdminService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Admin_AdminService.Method.SendNewsletter.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_SendNewsletterRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_SendNewsletterResponse>(),
            handler: { request, context in
                try await self.sendNewsletter(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Admin_AdminService.Method.SendNewsPush.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_SendNewsPushRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_SendNewsPushResponse>(),
            handler: { request, context in
                try await self.sendNewsPush(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Admin_AdminService.Method.CreateSupportRequest.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_CreateSupportRequestRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_CreateSupportRequestResponse>(),
            handler: { request, context in
                try await self.createSupportRequest(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Admin_AdminService.Method.ListSupportRequests.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_ListSupportRequestsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_ListSupportRequestsResponse>(),
            handler: { request, context in
                try await self.listSupportRequests(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Admin_AdminService.Method.ReplySupportRequest.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_ReplySupportRequestRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_ReplySupportRequestResponse>(),
            handler: { request, context in
                try await self.replySupportRequest(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Admin_AdminService.Method.ListUsers.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_ListUsersRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_ListUsersResponse>(),
            handler: { request, context in
                try await self.listUsers(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Admin_AdminService.Method.BanUser.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_BanUserRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_BanUserResponse>(),
            handler: { request, context in
                try await self.banUser(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Admin_AdminService.Method.UnbanUser.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_UnbanUserRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_UnbanUserResponse>(),
            handler: { request, context in
                try await self.unbanUser(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Admin_AdminService.ServiceProtocol {
    public func sendNewsletter(
        request: GRPCCore.StreamingServerRequest<Admin_SendNewsletterRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Admin_SendNewsletterResponse> {
        let response = try await self.sendNewsletter(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func sendNewsPush(
        request: GRPCCore.StreamingServerRequest<Admin_SendNewsPushRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Admin_SendNewsPushResponse> {
        let response = try await self.sendNewsPush(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func createSupportRequest(
        request: GRPCCore.StreamingServerRequest<Admin_CreateSupportRequestRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Admin_CreateSupportRequestResponse> {
        let response = try await self.createSupportRequest(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func listSupportRequests(
        request: GRPCCore.StreamingServerRequest<Admin_ListSupportRequestsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Admin_ListSupportRequestsResponse> {
        let response = try await self.listSupportRequests(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func replySupportRequest(
        request: GRPCCore.StreamingServerRequest<Admin_ReplySupportRequestRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Admin_ReplySupportRequestResponse> {
        let response = try await self.replySupportRequest(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func listUsers(
        request: GRPCCore.StreamingServerRequest<Admin_ListUsersRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Admin_ListUsersResponse> {
        let response = try await self.listUsers(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func banUser(
        request: GRPCCore.StreamingServerRequest<Admin_BanUserRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Admin_BanUserResponse> {
        let response = try await self.banUser(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func unbanUser(
        request: GRPCCore.StreamingServerRequest<Admin_UnbanUserRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Admin_UnbanUserResponse> {
        let response = try await self.unbanUser(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Admin_AdminService.SimpleServiceProtocol {
    public func sendNewsletter(
        request: GRPCCore.ServerRequest<Admin_SendNewsletterRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Admin_SendNewsletterResponse> {
        return GRPCCore.ServerResponse<Admin_SendNewsletterResponse>(
            message: try await self.sendNewsletter(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func sendNewsPush(
        request: GRPCCore.ServerRequest<Admin_SendNewsPushRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Admin_SendNewsPushResponse> {
        return GRPCCore.ServerResponse<Admin_SendNewsPushResponse>(
            message: try await self.sendNewsPush(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func createSupportRequest(
        request: GRPCCore.ServerRequest<Admin_CreateSupportRequestRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Admin_CreateSupportRequestResponse> {
        return GRPCCore.ServerResponse<Admin_CreateSupportRequestResponse>(
            message: try await self.createSupportRequest(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func listSupportRequests(
        request: GRPCCore.ServerRequest<Admin_ListSupportRequestsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Admin_ListSupportRequestsResponse> {
        return GRPCCore.ServerResponse<Admin_ListSupportRequestsResponse>(
            message: try await self.listSupportRequests(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func replySupportRequest(
        request: GRPCCore.ServerRequest<Admin_ReplySupportRequestRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Admin_ReplySupportRequestResponse> {
        return GRPCCore.ServerResponse<Admin_ReplySupportRequestResponse>(
            message: try await self.replySupportRequest(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func listUsers(
        request: GRPCCore.ServerRequest<Admin_ListUsersRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Admin_ListUsersResponse> {
        return GRPCCore.ServerResponse<Admin_ListUsersResponse>(
            message: try await self.listUsers(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func banUser(
        request: GRPCCore.ServerRequest<Admin_BanUserRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Admin_BanUserResponse> {
        return GRPCCore.ServerResponse<Admin_BanUserResponse>(
            message: try await self.banUser(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func unbanUser(
        request: GRPCCore.ServerRequest<Admin_UnbanUserRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Admin_UnbanUserResponse> {
        return GRPCCore.ServerResponse<Admin_UnbanUserResponse>(
            message: try await self.unbanUser(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: admin.AdminService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Admin_AdminService {
    /// Generated client protocol for the "admin.AdminService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "SendNewsletter" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_SendNewsletterRequest` message.
        ///   - serializer: A serializer for `Admin_SendNewsletterRequest` messages.
        ///   - deserializer: A deserializer for `Admin_SendNewsletterResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func sendNewsletter<Result>(
            request: GRPCCore.ClientRequest<Admin_SendNewsletterRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_SendNewsletterRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_SendNewsletterResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_SendNewsletterResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SendNewsPush" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_SendNewsPushRequest` message.
        ///   - serializer: A serializer for `Admin_SendNewsPushRequest` messages.
        ///   - deserializer: A deserializer for `Admin_SendNewsPushResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func sendNewsPush<Result>(
            request: GRPCCore.ClientRequest<Admin_SendNewsPushRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_SendNewsPushRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_SendNewsPushResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_SendNewsPushResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateSupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_CreateSupportRequestRequest` message.
        ///   - serializer: A serializer for `Admin_CreateSupportRequestRequest` messages.
        ///   - deserializer: A deserializer for `Admin_CreateSupportRequestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createSupportRequest<Result>(
            request: GRPCCore.ClientRequest<Admin_CreateSupportRequestRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_CreateSupportRequestRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_CreateSupportRequestResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_CreateSupportRequestResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListSupportRequests" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_ListSupportRequestsRequest` message.
        ///   - serializer: A serializer for `Admin_ListSupportRequestsRequest` messages.
        ///   - deserializer: A deserializer for `Admin_ListSupportRequestsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listSupportRequests<Result>(
            request: GRPCCore.ClientRequest<Admin_ListSupportRequestsRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_ListSupportRequestsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_ListSupportRequestsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ListSupportRequestsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ReplySupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_ReplySupportRequestRequest` message.
        ///   - serializer: A serializer for `Admin_ReplySupportRequestRequest` messages.
        ///   - deserializer: A deserializer for `Admin_ReplySupportRequestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func replySupportRequest<Result>(
            request: GRPCCore.ClientRequest<Admin_ReplySupportRequestRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_ReplySupportRequestRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_ReplySupportRequestResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ReplySupportRequestResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListUsers" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_ListUsersRequest` message.
        ///   - serializer: A serializer for `Admin_ListUsersRequest` messages.
        ///   - deserializer: A deserializer for `Admin_ListUsersResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listUsers<Result>(
            request: GRPCCore.ClientRequest<Admin_ListUsersRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_ListUsersRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_ListUsersResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ListUsersResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "BanUser" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_BanUserRequest` message.
        ///   - serializer: A serializer for `Admin_BanUserRequest` messages.
        ///   - deserializer: A deserializer for `Admin_BanUserResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func banUser<Result>(
            request: GRPCCore.ClientRequest<Admin_BanUserRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_BanUserRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_BanUserResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_BanUserResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UnbanUser" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_UnbanUserRequest` message.
        ///   - serializer: A serializer for `Admin_UnbanUserRequest` messages.
        ///   - deserializer: A deserializer for `Admin_UnbanUserResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func unbanUser<Result>(
            request: GRPCCore.ClientRequest<Admin_UnbanUserRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_UnbanUserRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_UnbanUserResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_UnbanUserResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "admin.AdminService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SendNewsletter" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_SendNewsletterRequest` message.
        ///   - serializer: A serializer for `Admin_SendNewsletterRequest` messages.
        ///   - deserializer: A deserializer for `Admin_SendNewsletterResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func sendNewsletter<Result>(
            request: GRPCCore.ClientRequest<Admin_SendNewsletterRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_SendNewsletterRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_SendNewsletterResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_SendNewsletterResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Admin_AdminService.Method.SendNewsletter.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SendNewsPush" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_SendNewsPushRequest` message.
        ///   - serializer: A serializer for `Admin_SendNewsPushRequest` messages.
        ///   - deserializer: A deserializer for `Admin_SendNewsPushResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func sendNewsPush<Result>(
            request: GRPCCore.ClientRequest<Admin_SendNewsPushRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_SendNewsPushRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_SendNewsPushResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_SendNewsPushResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Admin_AdminService.Method.SendNewsPush.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreateSupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_CreateSupportRequestRequest` message.
        ///   - serializer: A serializer for `Admin_CreateSupportRequestRequest` messages.
        ///   - deserializer: A deserializer for `Admin_CreateSupportRequestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func createSupportRequest<Result>(
            request: GRPCCore.ClientRequest<Admin_CreateSupportRequestRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_CreateSupportRequestRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_CreateSupportRequestResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_CreateSupportRequestResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Admin_AdminService.Method.CreateSupportRequest.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListSupportRequests" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_ListSupportRequestsRequest` message.
        ///   - serializer: A serializer for `Admin_ListSupportRequestsRequest` messages.
        ///   - deserializer: A deserializer for `Admin_ListSupportRequestsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listSupportRequests<Result>(
            request: GRPCCore.ClientRequest<Admin_ListSupportRequestsRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_ListSupportRequestsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_ListSupportRequestsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ListSupportRequestsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Admin_AdminService.Method.ListSupportRequests.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ReplySupportRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_ReplySupportRequestRequest` message.
        ///   - serializer: A serializer for `Admin_ReplySupportRequestRequest` messages.
        ///   - deserializer: A deserializer for `Admin_ReplySupportRequestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func replySupportRequest<Result>(
            request: GRPCCore.ClientRequest<Admin_ReplySupportRequestRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_ReplySupportRequestRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_ReplySupportRequestResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ReplySupportRequestResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Admin_AdminService.Method.ReplySupportRequest.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListUsers" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_ListUsersRequest` message.
        ///   - serializer: A serializer for `Admin_ListUsersRequest` messages.
        ///   - deserializer: A deserializer for `Admin_ListUsersResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listUsers<Result>(
            request: GRPCCore.ClientRequest<Admin_ListUsersRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_ListUsersRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_ListUsersResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ListUsersResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Admin_AdminService.Method.ListUsers.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "BanUser" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_BanUserRequest` message.
        ///   - serializer: A serializer for `Admin_BanUserRequest` messages.
        ///   - deserializer: A deserializer for `Admin_BanUserResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func banUser<Result>(
            request: GRPCCore.ClientRequest<Admin_BanUserRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_BanUserRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_BanUserResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_BanUserResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Admin_AdminService.Method.BanUser.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UnbanUser" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Admin_UnbanUserRequest` message.
        ///   - serializer: A serializer for `Admin_UnbanUserRequest` messages.
        ///   - deserializer: A deserializer for `Admin_UnbanUserResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func unbanUser<Result>(
            request: GRPCCore.ClientRequest<Admin_UnbanUserRequest>,
            serializer: some GRPCCore.MessageSerializer<Admin_UnbanUserRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Admin_UnbanUserResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_UnbanUserResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Admin_AdminService.Method.UnbanUser.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Admin_AdminService.ClientProtocol {
    /// Call the "SendNewsletter" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Admin_SendNewsletterRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sendNewsletter<Result>(
        request: GRPCCore.ClientRequest<Admin_SendNewsletterRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_SendNewsletterResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.sendNewsletter(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_SendNewsletterRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_SendNewsletterResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SendNewsPush" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Admin_SendNewsPushRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sendNewsPush<Result>(
        request: GRPCCore.ClientRequest<Admin_SendNewsPushRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_SendNewsPushResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.sendNewsPush(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_SendNewsPushRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_SendNewsPushResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateSupportRequest" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Admin_CreateSupportRequestRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createSupportRequest<Result>(
        request: GRPCCore.ClientRequest<Admin_CreateSupportRequestRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_CreateSupportRequestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createSupportRequest(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_CreateSupportRequestRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_CreateSupportRequestResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListSupportRequests" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Admin_ListSupportRequestsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listSupportRequests<Result>(
        request: GRPCCore.ClientRequest<Admin_ListSupportRequestsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ListSupportRequestsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listSupportRequests(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_ListSupportRequestsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_ListSupportRequestsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ReplySupportRequest" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Admin_ReplySupportRequestRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func replySupportRequest<Result>(
        request: GRPCCore.ClientRequest<Admin_ReplySupportRequestRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ReplySupportRequestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.replySupportRequest(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_ReplySupportRequestRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_ReplySupportRequestResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListUsers" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Admin_ListUsersRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listUsers<Result>(
        request: GRPCCore.ClientRequest<Admin_ListUsersRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ListUsersResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listUsers(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_ListUsersRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_ListUsersResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "BanUser" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Admin_BanUserRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func banUser<Result>(
        request: GRPCCore.ClientRequest<Admin_BanUserRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_BanUserResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.banUser(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_BanUserRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_BanUserResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UnbanUser" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Admin_UnbanUserRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unbanUser<Result>(
        request: GRPCCore.ClientRequest<Admin_UnbanUserRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_UnbanUserResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.unbanUser(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Admin_UnbanUserRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Admin_UnbanUserResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Admin_AdminService.ClientProtocol {
    /// Call the "SendNewsletter" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sendNewsletter<Result>(
        _ message: Admin_SendNewsletterRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_SendNewsletterResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Admin_SendNewsletterRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.sendNewsletter(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SendNewsPush" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sendNewsPush<Result>(
        _ message: Admin_SendNewsPushRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_SendNewsPushResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Admin_SendNewsPushRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.sendNewsPush(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateSupportRequest" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createSupportRequest<Result>(
        _ message: Admin_CreateSupportRequestRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_CreateSupportRequestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Admin_CreateSupportRequestRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createSupportRequest(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListSupportRequests" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listSupportRequests<Result>(
        _ message: Admin_ListSupportRequestsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ListSupportRequestsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Admin_ListSupportRequestsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listSupportRequests(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ReplySupportRequest" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func replySupportRequest<Result>(
        _ message: Admin_ReplySupportRequestRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ReplySupportRequestResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Admin_ReplySupportRequestRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.replySupportRequest(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListUsers" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listUsers<Result>(
        _ message: Admin_ListUsersRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_ListUsersResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Admin_ListUsersRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listUsers(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "BanUser" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func banUser<Result>(
        _ message: Admin_BanUserRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_BanUserResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Admin_BanUserRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.banUser(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UnbanUser" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unbanUser<Result>(
        _ message: Admin_UnbanUserRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Admin_UnbanUserResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Admin_UnbanUserRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.unbanUser(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}